language: python

python:
- "3.5"

cache: pip

addons:
  apt:
    packages:
    - libpq-dev

env:
  global:
  - ENV=TEST
  - ADDRESS=0.0.0.0
  - PORT=10000
  - MASTER_DOMAIN=ocelot.com
  - MIGRATIONS_PATH=migrations
  - DATABASE_URL=null
  - CLIENTS=null
  - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/src

install:
- pip install -r requirements.txt

script:
- coverage run --source=actions --module unittest discover --verbose

after_success:
- coveralls

deploy:
- provider: script
  skip_cleanup: true
  script: bin/togemfury.sh
- provider: heroku
  app: ocelot-saas-actions
  api_key:
    secure: "M5mBEYwvL0dhKoFVMXJQMRENiV8B2YZqMCu95KBRdw3XxDg65UO27HYX33GK+svr7YI2x94shg2ly+jdpqaXGbg+lIqZidh+mTFwGSHabsxCJtMHoSGbpv1ZpATU32YkYG5Hc7E98uRKzMxTavqM4lyZL+MCOY1JBuTjfTdzXkUShgVQcqHuFVcjZNp/e7/llJqA4VPKGhdy8tmqzPtzgbHaPv54McuyS9VuHkkZTawzU6+ewZsk3EpgrGmJ3b0tT8Qa6ZN6c0mlnKqokgCAGcWXpOYn0gK6qD//ioNF12LEyNi+OUWNdNYTbZjAk1dFhinelSORVz1u8UfLj5znB3XuhT8ruZI36+PAPq5/qnX5nfLRN/b6oSuSb8Y3fjAE95M7de4RKcuHyc+TnlDXWIbGp/dpFTbnlAANnL7QFIJCr5ZLBtcvX4+QwFB2qJO2PPPrYoqL+QiHAwoV70PXydrciBLyfhr70yAFxiy/KWkk/w5/28ljS+LcmZAPerSAszj92m/PiE7SNQg74jw7TDM8SdAxaI4RVUkK+bMucYBo8aCur4cBWsaYoOILNoSOaX9aqgpcUno0OYw8/IZqB/+7xNPhazfzct9yd/eDNdiefQ0Y7NCxVJ/j0CVFZg3gLcGhunaSRyTpgyBeuKiilS2ArDdqz/keL35FRe12ULA="
